sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
- cd $HOME && mkdir twrp
- wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-20180211/omni_twrp-5.1.1-20180211-norepo.tar.xz
  -O $HOME/twrp.tar.xz
- tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/TwrpBuilder/android_device_a5y17lte.git device/samsung/a5y17lte
  - git clone https://github.com/TwrpBuilder/device_generic_twrpbuilder.git device/generic/twrpbuilder
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_a5y17lte-userdebug && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/a5y17lte/recovery.img $HOME/twrp/TWRP-$version-a5y17lte-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: TwrpBuilder/android_device_a5y17lte
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
